import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "MindzFlair",
  description: "Generated by create next app",
   openGraph: {
    title: "MindzFlair",
    description: "Clone your face and voice. Live forever with AI.",
    images: [
      {
        url: "/logo.png",
        width: 1200,
        height: 630,
        alt: "MindzFlair",
      },
    ],
  },
  icons: {
    icon: "/logo2.png", // also place in public/
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" >
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
